trigger:
- main

pool:
    vmImage: ubuntu-latest

variables:
    buildConfiguration: 'Release'

steps:
    - script: dotnet build --configuration $(buildConfigutaion)
        displayName:'dotnet build $(buildConfiguration)'
